// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: 2025_project

#ifndef _2025_PROJECT_UI_H
#define _2025_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TextArea2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_BTN5(lv_event_t * e);
extern lv_obj_t * ui_BTN5;
extern lv_obj_t * ui_BTN4;
extern lv_obj_t * ui_BTN3;
extern lv_obj_t * ui_BTN2;
extern lv_obj_t * ui_BTN1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_labelbtn4;
extern lv_obj_t * ui_labelbtn3;
extern lv_obj_t * ui_labelbtn2;
extern lv_obj_t * ui_labelbtn1;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_group_2946_png);    // assets/Group 2946.png
LV_IMG_DECLARE(ui_img_group_2945_png);    // assets/Group 2945.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
