// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: 2025_project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTN5 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BTN5, 100);
    lv_obj_set_height(ui_BTN5, 50);
    lv_obj_set_x(ui_BTN5, -2);
    lv_obj_set_y(ui_BTN5, 174);
    lv_obj_set_align(ui_BTN5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTN5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTN4 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BTN4, 91);
    lv_obj_set_height(ui_BTN4, 39);
    lv_obj_set_x(ui_BTN4, 78);
    lv_obj_set_y(ui_BTN4, 98);
    lv_obj_set_align(ui_BTN4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTN4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTN3 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BTN3, 91);
    lv_obj_set_height(ui_BTN3, 42);
    lv_obj_set_x(ui_BTN3, -80);
    lv_obj_set_y(ui_BTN3, 96);
    lv_obj_set_align(ui_BTN3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTN3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTN2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BTN2, 95);
    lv_obj_set_height(ui_BTN2, 40);
    lv_obj_set_x(ui_BTN2, 78);
    lv_obj_set_y(ui_BTN2, -29);
    lv_obj_set_align(ui_BTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTN2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTN1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BTN1, 91);
    lv_obj_set_height(ui_BTN1, 43);
    lv_obj_set_x(ui_BTN1, -80);
    lv_obj_set_y(ui_BTN1, -28);
    lv_obj_set_align(ui_BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image2, &ui_img_group_2945_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelbtn4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelbtn4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelbtn4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelbtn4, 78);
    lv_obj_set_y(ui_labelbtn4, 97);
    lv_obj_set_align(ui_labelbtn4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelbtn4, "BTN4");

    ui_labelbtn3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelbtn3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelbtn3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelbtn3, -89);
    lv_obj_set_y(ui_labelbtn3, 98);
    lv_obj_set_align(ui_labelbtn3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelbtn3, "BTN3");

    ui_labelbtn2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelbtn2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelbtn2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelbtn2, 75);
    lv_obj_set_y(ui_labelbtn2, -25);
    lv_obj_set_align(ui_labelbtn2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelbtn2, "BTN2");

    ui_labelbtn1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelbtn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelbtn1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelbtn1, -83);
    lv_obj_set_y(ui_labelbtn1, -28);
    lv_obj_set_align(ui_labelbtn1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelbtn1, "BTN1 ");
    lv_obj_set_style_text_color(ui_labelbtn1, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelbtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, 173);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "SETTING");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFF0015), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTN5, ui_event_BTN5, LV_EVENT_ALL, NULL);

}
